# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 540)
        Login.setMinimumSize(QtCore.QSize(800, 540))
        Login.setMaximumSize(QtCore.QSize(800, 540))
        font = QtGui.QFont()
        font.setFamily("宋体")
        Login.setFont(font)
        Login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox = QtWidgets.QGroupBox(Login)
        self.groupBox.setGeometry(QtCore.QRect(450, 190, 266, 201))
        self.groupBox.setMinimumSize(QtCore.QSize(266, 201))
        self.groupBox.setMaximumSize(QtCore.QSize(266, 201))
        self.groupBox.setStyleSheet("background-color: rgba(255,255,255,0.5);")
        self.groupBox.setObjectName("groupBox")
        self.enter = QtWidgets.QFormLayout(self.groupBox)
        self.enter.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.enter.setContentsMargins(20, 20, 20, 0)
        self.enter.setSpacing(20)
        self.enter.setObjectName("enter")
        self.number = QtWidgets.QLabel(self.groupBox)
        self.number.setMinimumSize(QtCore.QSize(40, 24))
        self.number.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.number.setFont(font)
        self.number.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.number.setStyleSheet("background-color: rgba(255,255,255,o);")
        self.number.setObjectName("number")
        self.enter.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.number)
        self.number_in = QtWidgets.QLineEdit(self.groupBox)
        self.number_in.setMinimumSize(QtCore.QSize(161, 21))
        self.number_in.setMaximumSize(QtCore.QSize(161, 21))
        self.number_in.setObjectName("number_in")
        self.enter.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_in)
        self.password = QtWidgets.QLabel(self.groupBox)
        self.password.setMinimumSize(QtCore.QSize(40, 24))
        self.password.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.password.setObjectName("password")
        self.enter.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password)
        self.password_in = QtWidgets.QLineEdit(self.groupBox)
        self.password_in.setMinimumSize(QtCore.QSize(161, 21))
        self.password_in.setMaximumSize(QtCore.QSize(161, 21))
        self.password_in.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_in.setObjectName("password_in")
        self.enter.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_in)
        self.button = QtWidgets.QFormLayout()
        self.button.setContentsMargins(10, 10, 10, 10)
        self.button.setSpacing(10)
        self.button.setObjectName("button")
        self.loginbutton = QtWidgets.QPushButton(self.groupBox)
        self.loginbutton.setMinimumSize(QtCore.QSize(93, 28))
        self.loginbutton.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("background-color: rgba(244, 255, 255, 0.8);")
        self.loginbutton.setObjectName("loginbutton")
        self.button.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.loginbutton)
        self.cancelloginbutton = QtWidgets.QPushButton(self.groupBox)
        self.cancelloginbutton.setMinimumSize(QtCore.QSize(93, 28))
        self.cancelloginbutton.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelloginbutton.setFont(font)
        self.cancelloginbutton.setStyleSheet("background-color: rgba(244, 255, 255, 0);")
        self.cancelloginbutton.setObjectName("cancelloginbutton")
        self.button.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cancelloginbutton)
        self.enter.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.button)
        self.border_image = QtWidgets.QListView(Login)
        self.border_image.setGeometry(QtCore.QRect(50, 110, 700, 370))
        self.border_image.setMinimumSize(QtCore.QSize(700, 370))
        self.border_image.setMaximumSize(QtCore.QSize(700, 370))
        self.border_image.setStyleSheet("border-image: url(:/school.jpg);")
        self.border_image.setObjectName("border_image")
        self.title = QtWidgets.QLabel(Login)
        self.title.setGeometry(QtCore.QRect(250, 30, 471, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("font: 16pt \"华文楷体\";\n"
"color: rgb(0, 0, 235);")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.calibration = QtWidgets.QListView(Login)
        self.calibration.setGeometry(QtCore.QRect(10, 20, 241, 81))
        self.calibration.setStyleSheet("border-image: url(:/calibration.png);")
        self.calibration.setObjectName("calibration")
        self.registerbutton = QtWidgets.QPushButton(Login)
        self.registerbutton.setGeometry(QtCore.QRect(660, 87, 93, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.registerbutton.setFont(font)
        self.registerbutton.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(88, 88, 88);")
        self.registerbutton.setObjectName("registerbutton")
        self.line = QtWidgets.QFrame(Login)
        self.line.setGeometry(QtCore.QRect(20, 490, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.border_image.raise_()
        self.groupBox.raise_()
        self.title.raise_()
        self.calibration.raise_()
        self.registerbutton.raise_()
        self.line.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登录"))
        self.number.setText(_translate("Login", "账号"))
        self.password.setText(_translate("Login", "密码"))
        self.loginbutton.setText(_translate("Login", "登录"))
        self.cancelloginbutton.setText(_translate("Login", "取消"))
        self.title.setText(_translate("Login", "目标位姿标注虚拟仿真平台"))
        self.registerbutton.setText(_translate("Login", "注册"))
import picture
