# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(800, 540)
        Register.setMinimumSize(QtCore.QSize(800, 540))
        Register.setMaximumSize(QtCore.QSize(800, 540))
        font = QtGui.QFont()
        font.setFamily("宋体")
        Register.setFont(font)
        Register.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.border_image = QtWidgets.QListView(Register)
        self.border_image.setGeometry(QtCore.QRect(50, 110, 700, 370))
        self.border_image.setMinimumSize(QtCore.QSize(700, 370))
        self.border_image.setMaximumSize(QtCore.QSize(700, 370))
        self.border_image.setStyleSheet("border-image: url(:/school.jpg);")
        self.border_image.setObjectName("border_image")
        self.title = QtWidgets.QLabel(Register)
        self.title.setGeometry(QtCore.QRect(250, 30, 471, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("font: 16pt \"华文楷体\";\n"
"color: rgb(0, 0, 235);")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.calibration = QtWidgets.QListView(Register)
        self.calibration.setGeometry(QtCore.QRect(10, 20, 241, 81))
        self.calibration.setStyleSheet("border-image: url(:/calibration.png);")
        self.calibration.setObjectName("calibration")
        self.line = QtWidgets.QFrame(Register)
        self.line.setGeometry(QtCore.QRect(20, 490, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(Register)
        self.groupBox.setGeometry(QtCore.QRect(430, 160, 287, 231))
        self.groupBox.setMinimumSize(QtCore.QSize(287, 231))
        self.groupBox.setMaximumSize(QtCore.QSize(287, 231))
        self.groupBox.setStyleSheet("background-color: rgba(255,255,255,0.5);")
        self.groupBox.setObjectName("groupBox")
        self.enter = QtWidgets.QFormLayout(self.groupBox)
        self.enter.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.enter.setContentsMargins(20, 20, 15, 15)
        self.enter.setSpacing(20)
        self.enter.setObjectName("enter")
        self.number = QtWidgets.QLabel(self.groupBox)
        self.number.setMinimumSize(QtCore.QSize(40, 24))
        self.number.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.number.setFont(font)
        self.number.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.number.setStyleSheet("background-color: rgba(255,255,255,o);")
        self.number.setObjectName("number")
        self.enter.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.number)
        self.number_in = QtWidgets.QLineEdit(self.groupBox)
        self.number_in.setMinimumSize(QtCore.QSize(161, 21))
        self.number_in.setMaximumSize(QtCore.QSize(161, 21))
        self.number_in.setObjectName("number_in")
        self.enter.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_in)
        self.password = QtWidgets.QLabel(self.groupBox)
        self.password.setMinimumSize(QtCore.QSize(40, 24))
        self.password.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.password.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.password.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.password.setObjectName("password")
        self.enter.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password)
        self.password_in = QtWidgets.QLineEdit(self.groupBox)
        self.password_in.setMinimumSize(QtCore.QSize(161, 21))
        self.password_in.setMaximumSize(QtCore.QSize(161, 21))
        self.password_in.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_in.setObjectName("password_in")
        self.enter.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_in)
        self.phone = QtWidgets.QLabel(self.groupBox)
        self.phone.setMinimumSize(QtCore.QSize(40, 24))
        self.phone.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.phone.setFont(font)
        self.phone.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.phone.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.phone.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.phone.setObjectName("phone")
        self.enter.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.phone_in = QtWidgets.QLineEdit(self.groupBox)
        self.phone_in.setMinimumSize(QtCore.QSize(161, 21))
        self.phone_in.setMaximumSize(QtCore.QSize(161, 21))
        self.phone_in.setObjectName("phone_in")
        self.enter.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phone_in)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.registerbutton = QtWidgets.QPushButton(self.groupBox)
        self.registerbutton.setMinimumSize(QtCore.QSize(93, 28))
        self.registerbutton.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerbutton.setFont(font)
        self.registerbutton.setStyleSheet("background-color: rgb(244, 255, 255);")
        self.registerbutton.setObjectName("registerbutton")
        self.gridLayout.addWidget(self.registerbutton, 0, 0, 1, 1)
        self.cancelregisterbutton = QtWidgets.QPushButton(self.groupBox)
        self.cancelregisterbutton.setMinimumSize(QtCore.QSize(93, 28))
        self.cancelregisterbutton.setMaximumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelregisterbutton.setFont(font)
        self.cancelregisterbutton.setStyleSheet("background-color: rgba(244, 255, 255, 0);")
        self.cancelregisterbutton.setObjectName("cancelregisterbutton")
        self.gridLayout.addWidget(self.cancelregisterbutton, 0, 1, 1, 1)
        self.enter.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "注册"))
        self.title.setText(_translate("Register", "基于三维模型的车辆位姿估计标注系统"))
        self.number.setText(_translate("Register", "账号"))
        self.password.setText(_translate("Register", "密码"))
        self.phone.setText(_translate("Register", "电话"))
        self.registerbutton.setText(_translate("Register", "注册"))
        self.cancelregisterbutton.setText(_translate("Register", "取消"))
import picture
